import React from "react";
import Head from "next/head";
import Footer from "../../common/Footer";
import Topbar from "../../common/Topbar";
import LayoutHeader from "../header/LayoutHeader";
import Header from "../header/Header";
function Layout({ children }) {
  return (
    <>
      <Head>
        <title>
          Diamond Back Funding- Law firm, Lawyers & Legal Service React NextJs Template
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="assets/images/icons/logo-icon.svg" />
      </Head>
      {/* <Topbar /> */}
      <Header logoLeft={`<Link href="/"><a><img alt="image" src="assets/images/icons/header1-logo.png" /></a></Link>`} styles="header-area style-1" />
      {children}
      <Footer />
    </>
  );
}

export default Layout;
